aminalaee/mongox

.github/workflows/publish.yml
.github/workflows/test-suite.yml
README.md
docs/index.md
mongox/fields.py
mongox/models.py
poetry.lock
pyproject.toml

GitHub Actions for test and publish.

Github Actions

---

docs/queriying_documents.md
mongox/__init__.py
mongox/expressions.py
mongox/fields.py
mongox/models.py
tests/test_models.py

Making use of QueryExpression and SortExpression as data models.

Introduce QueryExpression and SortExpression

---

mongox/index.py
tests/test_models.py

- Replaces assignments with augmented assignments
- Replaces conditional assignment to a variable with an if expression

refactor code expression

---

docs/queriying_documents.md
mongox/__init__.py
mongox/expressions.py
mongox/models.py
tests/test_models.py

Adding `in_` and `not_in` Q operators.
Examples:
```python
movies = await Movie.query(Q.in_(Movie.year, [2000, 2001, 2002])).all()
movies = (
await Movie.query(Movie.year > 2000)
.query(Movie.year <= 2010)
.query(Q.not_in(Movie.year, [2001, 2002]))
.all()
)
```

Extend Q operator

---

docs/cheat_sheet.md
docs/defining_documents.md
docs/queriying_documents.md
mkdocs.yml
mongox/index.py

Adds documentation for Q and Indexes.

Add Index and Q docs

---

README.md
docs/cheat_sheet.md
docs/defining_documents.md
docs/index.md
mongox/models.py
tests/test_indexes.py
tests/test_models.py

Adding `drop_index` and `drop_indexes` collection-level methods.

Add drop_index and drop_indexes methods

---

mongox/__init__.py
pyproject.toml

Version 0.0.2
https://github.com/aminalaee/mongox/releases/edit/untagged-90508360c4e324722a9e

Version 0.0.2

---

docs/cheat_sheet.md
docs/defining_documents.md
docs/queriying_documents.md
examples/embedded_models.py
mongox/__init__.py
mongox/expressions.py
mongox/fields.py
mongox/models.py
tests/test_embedded_models.py
tests/test_models.py

Adds `EmbeddedModel`:
```python
class Genre(EmbeddedModel):
title: str
class Movie(Model):
name: str
genre: Genre
year: int
genre = Genre(title="Action")
await Movie(
name="Saving Private Ryan",
year=1990,
genre=genre,
).insert()
movie = await Movie.query(Movie.genre.title == "Action").get()
assert movie.name == "Saving Private Ryan"
movie = await Movie.query(Movie.genre == genre).get()
assert movie.name == "Saving Private Ryan"
```

Add EmbeddedModel

---

mongox/models.py
poetry.lock
pyproject.toml
tests/test_integrations.py
tests/test_models.py

Integration tests

---

docs/queriying_documents.md

The example model is corrected in the documentation of embedded models.

Documentation of embedded models

---

docs/queriying_documents.md
mongox/models.py
tests/test_models.py

add `get_or_create`:
```python
class Movie(mongox.Model):
name: str
year: int
class Meta:
collection = db.get_collection("movies")
movie = await Movie.query({Movie.name: "Forrest Gump"}).get_or_create({Movie.year: 2003})
assert movie.name == "Forrest Gump"
assert movie.year == 2003
```

Get or Create method

---

docs/queriying_documents.md
mongox/models.py
tests/test_models.py

Internal change to make tests independent of each other.

Improve test_models to be independant

---

docs/queriying_documents.md
mongox/models.py
tests/test_models.py

Hey @aminalaee,
This would be the solution to bug #27, I still have to update the documentation but first I would like to know what do you think about the solution?

Correction of the bug in the return of the update

---

mongox/__init__.py
mongox/models.py
poetry.lock
pyproject.toml

* `get_or_create` method by @MAD-py in https://github.com/aminalaee/mongox/pull/23
* Avoid `Meta` class from Model definition by @aminalaee in https://github.com/aminalaee/mongox/pull/25
* Fix bulk update return by @MAD-py in https://github.com/aminalaee/mongox/pull/29
* Fixed autouse fixtures by @kuutsav in https://github.com/aminalaee/mongox/pull/26
* @MAD-py made their first contribution in https://github.com/aminalaee/mongox/pull/21
* @kuutsav made their first contribution in https://github.com/aminalaee/mongox/pull/26
**Full Changelog**: https://github.com/aminalaee/mongox/compare/0.0.3...0.1.0

Version 0.1.0

---

mongox/models.py
tests/test_models.py

This PR would be the solution to issue #33

Add Pydantic validation to `get_or_create` method

---

docs/queriying_documents.md
mongox/database.py
mongox/expressions.py
mongox/fields.py
mongox/index.py
mongox/models.py
tests/test_models.py

Closes #36 
```python
models = Model.query()
async for model in models:
print(model)
models = await Model.query().all()
```

Expose Async Generator in Queryset

---

docs/queriying_documents.md
mongox/exceptions.py
mongox/models.py
tests/test_models.py

Add `get_by_id` method for Model

Feat: add get_by_id method

---

mongox/database.py
mongox/expressions.py
mongox/models.py

Just fix some spelling mistakes when I review the code😜

Chore: just fix spelling mistake and some

---

docs/queriying_documents.md
mongox/models.py
tests/test_models.py

Closes #31
```python
movies = await Movie.query(Q.contains(Movie.tags, "Drama")).all()
```

Add `Q` method `contains` for lists and strings

---

docs/queriying_documents.md
mongox/exceptions.py
mongox/models.py
tests/test_models.py

Closes #44
```py
movies = await Movie.query(Q.regex(Movie.name, re.compile(".[0-9]$"))).all()
```

Add Q method `regex` for matched strings

---

mongox/models.py
tests/test_multiple_models.py

Bugfix for https://github.com/aminalaee/mongox/issues/86 (Error when working with multiple models)

For each Modelclass a new Meta instance will be created
